{{- if .Values.ssl.cert_manager.enabled }}
{{- $r53 := .Values.ssl.cert_manager.dns01.route53 | default dict }}
{{- if and (not ($r53.use_iam_role | default false)) $r53.secret_access_key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: route53-credentials
  namespace: cert-manager
type: Opaque
stringData:
  secret-access-key: {{ $r53.secret_access_key | quote }}
{{- end }}
{{- end }}

